### ISSUE TITLE
AccessDenied component

### ISSUE THREAD

**Issue by magnusjt** [tfso/react-tfso-components#15]
We need a nice component to show whenever the user does not have access to a given route.

The current implementation:
https://github.com/tfso/react-website-boilerplate/blob/master/client/src/modules/layout/components/AccessDenied.tsx

The component should provide info on how to get the required accesses (link to https://upgrade.24sevenoffice.com/no/modules/bank/ etc).

**Comment by steinarj** [comment]
AccessDeniedDemo
- Missing description of props
- Go back function should output description to demo page
- HandleIncrement does not give any meaning to the function for Clicking the button


AccessDenied
- styled button should not have fixed color, use theme to pick the right color
- Change styles to use styled.components
- Should take translate as a prop so text can be translated.

**Comment by steinarj** [comment]
Completed
