### ISSUE TITLE
board compoent

### ISSUE THREAD

**Issue by steinarj** [tfso/react-tfso-components#16]
It seems that when compacting the layout the sorting of boxes is done in a strange way.
Sort order seems off

**Comment by sondresj** [comment]
![bilde](https://user-images.githubusercontent.com/44254105/60490325-9af89f80-9ca6-11e9-890c-df0f44fb98b4.png)

The components keeps a different layout for different screen-sizes (mobile, tablet and desktop). When you resize the browser, a different layout is shown. You can rearrange the board as you like for the different screen-sizes. 

Compaction is a term used for removing empty areas between items on the board, this is done vertically (items are moved upwards if there is space for it)
